Repository amit-56/Hacktoberfest-Projects, pull requests merged in 2022-09, with the labels that each got.

#1 added bit manipulation program
  Algorithms/C++/bit_manipulation/count_bits_flip.cpp
Labels: enhancement

#2 readme update
  README.md
Labels: documentation

#9 A personal to do task app using streamlit python
  Projects/WEB_PROJECT/To-Do Task app/README.md
  Projects/WEB_PROJECT/To-Do Task app/app.py
  Projects/WEB_PROJECT/To-Do Task app/data.db
  Projects/WEB_PROJECT/To-Do Task app/data1.db
  Projects/WEB_PROJECT/To-Do Task app/db1.py
  Projects/WEB_PROJECT/To-Do Task app/requirements.txt
  Projects/WEB_PROJECT/To-Do Task app/we.png
Labels: hacktoberfest-accepted

#15 Added portofolio application
  Projects/WEB_PROJECT/portofolio-main/CNAME
  Projects/WEB_PROJECT/portofolio-main/index.html
  Projects/WEB_PROJECT/portofolio-main/main.js
  Projects/WEB_PROJECT/portofolio-main/scsw.jpg
  Projects/WEB_PROJECT/portofolio-main/style.css
Labels: hacktoberfest-accepted

#19 Added Automated Security Camera application
  Projects/Programming_language_projects/Python/automated-security-camera.py
Labels: hacktoberfest-accepted

#18 Create linear_search.py
  Algorithms/Python/searching/linear_search.py
Labels: hacktoberfest-accepted

#17 Added stack queue and Linked List implementation in C++
  Algorithms/C++/data_structures/LinkedList.cpp
  Algorithms/C++/data_structures/Queues.cpp
  Algorithms/C++/data_structures/Stacks.cpp
Labels: hacktoberfest-accepted

#16 SelectionSort algo added
  selectionSort.cpp
Labels: hacktoberfest-accepted
